image:
  file: .gitpod.Dockerfile

ports:
  # IHP Server
  - port: 8000
    onOpen: open-browser
  # IDE
  - port: 8001
    onOpen: open-browser

tasks:
  - init: >
      ( if [ ! -e "Main.hs" ]; then ( if [ -e "/tmp/ihp-boilerplate" ]; then rm -rf /tmp/ihp-boilerplate; fi); mkdir -p /tmp/ihp-boilerplate; cd /tmp/ihp-boilerplate; git clone https://github.com/digitallyinduced/ihp-boilerplate.git; rm -rf .git; nix-shell -j auto --cores 0 --quiet --run 'make -s all .envrc; new-application Web'; fi) && cd - && cp -r /tmp/ihp-boilerplate . && nix-shell -j auto --cores 0 --run 'make -s all .envrc' && direnv allow
    command: >
      export IHP_BASEURL=`gp url 8000`;
      export IHP_IDE_BASEURL=`gp url 8001`;
      ./start

vscode:
  extensions:
    - haskell.haskell
    - s0kil.vscode-hsx
    - arrterian.nix-env-selector

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
